eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8080/eureka/
server:
  port: 8084
spring:
  application:
    name: service-feign
  main:
    allow-bean-definition-overriding: true

  thymeleaf:
    encoding: UTF-8
    servlet:
      content-type: text/html

  ribbon:
    eureka:
      enabled: true
  feign:
    hystrix:
      enabled: true