server:
  port: 8082
spring:
  application:
    name: service-hi
  datasource:
    password: 123
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=utf-8
    username: root
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8080/eureka/
mybatis:
  config-locations: classpath:mybatis/confg.xml
  mapper-locations: classpath:mybatis/mapper/*.xml

  instance:
    lease-renewal-interval-in-seconds: 1
    lease-expiration-duration-in-seconds: 2

